Switch from upper to lower case answers in setup

diff --git a/configs/setup b/configs/setup
--- a/configs/setup
+++ b/configs/setup
@@ -51,14 +51,14 @@ startnet()
 
 	echo "Do you wish to use static or dynamic IP assignment?"
 	echo
-	echo -n "Enter STATIC or DYNAMIC (all upper case): "
+	echo -n "Enter 'static' or 'dynamic': "
 	unset STATDYN
 	read STATDYN
 
 	killall -9 udhcpc 2>/dev/null
 	echo -n > /etc/resolv.conf
 
-	if [ "x$STATDYN" = "xSTATIC" ]
+	if [ "x$STATDYN" = "xstatic" ]
 	then
 
 	########################################################################
@@ -99,17 +99,17 @@ startnet()
 
 	#########################################################################
 
-	elif [ "x$STATDYN" = "xDYNAMIC" ]
+	elif [ "x$STATDYN" = "xdynamic" ]
 	then
 
 		echo
 		echo "Do you want to specify a DNS server, or use the one offered by DHCP?"
-		echo -n "Enter YES to specify a DNS server, NO to use the one offered (all upper case):"
+		echo -n "Enter 'yes' to specify a DNS server, 'no' to use the one offered:"
 		unset DNS
 		read DNS
 
 
-		if [ "x$DNS" = "xYES" ]
+		if [ "x$DNS" = "xyes" ]
 		then
 			ifconfig $ETH up
 			udhcpc -i $ETH -s /etc/udhcpc.nodns 2>&1 || return 6
@@ -121,15 +121,18 @@ startnet()
 			echo "nameserver $NAME" > /etc/resolv.conf
 			nslookup www.google.com >/dev/null 2>&1 || return 5
 
-		else
+		elif [ "x$DNS" = "xno" ]
 			ifconfig $ETH up
 			udhcpc -i $ETH -s /etc/udhcpc 2>&1 || return 6
+		else
+			echo "Please specify whether you want to specify a DNS server, or use the one offered."
+			return 7
 		fi
 
 	else
 
-		echo "Please specify whether you want to use STATIC or DYNAMIC ip assignment."
-		return 7
+		echo "Please specify whether you want to use 'static' or 'dynamic' ip assignment."
+		return 8
 
 	fi
 
@@ -152,9 +155,9 @@ importing()
 	echo "*** IMPORTING/GENERATING TORRC *** "
 	echo 
 	echo "Do you want to import a torrc or generate one?"
-	echo "NOTE: only FTP and SCP are supported"
+	echo "NOTE: Only ftp and scp are supported"
 	echo
-	echo -n "Enter IMPORT or GENERATE (all upper case): "
+	echo -n "Enter 'import' or 'generate': "
 	if [ -f /etc/tor/torrc ]
 	then
 		echo
@@ -165,17 +168,17 @@ importing()
 	unset IMPORTTORRC
 	read IMPORTTORRC
 
-	if [ "x$IMPORTTORRC" = "xIMPORT" ]
+	if [ "x$IMPORTTORRC" = "ximport" ]
 	then
 
 		echo "Importing torrc ..."
 		echo
 
-		echo -n "Enter FTP or SCP (all upper case):"
+		echo -n "Enter 'ftp' or 'scp':"
 		unset FTP
 		read FTP
 
-		echo -n "Enter the hostname/IP of the FTP/SSH server: "
+		echo -n "Enter the hostname/IP of the ftp/ssh server: "
 		unset HOST
 		read HOST
 	
@@ -183,13 +186,13 @@ importing()
 		unset FTPPATH
 		read FTPPATH
 
-		echo -n "Enter the username (or anonymous) of the FTP/SSH account: "
+		echo -n "Enter the username (or anonymous) of the ftp/ssh account: "
 		unset USER
 		read USER
 
-		if [ "x$FTP" = "xFTP" ]
+		if [ "x$FTP" = "xftp" ]
 		then
-			echo -n "Enter the password of the FTP account (will not echo): "
+			echo -n "Enter the password of the ftp account (will not echo): "
 			unset PASS
 			stty -echo
 			read PASS
@@ -198,11 +201,11 @@ importing()
 
 			ftpget -u $USER -p $PASS $HOST /etc/tor/torrc $FTPPATH || return 1
 
-		elif [ "x$FTP" = "xSCP" ] 
+		elif [ "x$FTP" = "xscp" ] 
 		then
 			scp $USER@$HOST:$FTPPATH /etc/tor/torrc || return 1
 		else
-			echo "Please specify whether you want to use FTP or SCP."
+			echo "Please specify whether you want to use 'ftp' or 'scp'."
 			return 1
 		fi
 
@@ -210,7 +213,7 @@ importing()
 		echo "<torrc successfully imported>"
 		echo
 
-	elif [ "x$IMPORTTORRC" = "xGENERATE" ]
+	elif [ "x$IMPORTTORRC" = "xgenerate" ]
 	then
 
 		echo "Generating a new torrc ..."
@@ -239,24 +242,24 @@ importing()
 
 		echo
 		echo "Do you want to run as an directory server?"
-		echo "Enter DIRECTORY (all upper case) if you do"
+		echo "Enter 'directory' if you do"
 		echo -n "or just hit enter if you don't: "
 		unset DIRECTORY
 		read DIRECTORY
 
-		if [ "x$DIRECTORY" = "xDIRECTORY" ]
+		if [ "x$DIRECTORY" = "xdirectory" ]
 		then
 			echo "DirPort 9030" >> /etc/tor/torrc
 		fi
 
 		echo
 		echo "Do you want to run as an exit node?"
-		echo "Enter EXIT (all upper case) if you do"
+		echo "Enter 'exit' if you do"
 		echo -n "or just hit enter if you don't: "
 		unset EXIT
 		read EXIT
 
-		if [ "x$EXIT" != "xEXIT" ]
+		if [ "x$EXIT" != "xexit" ]
 		then
 			echo "ExitPolicy reject *:*" >> /etc/tor/torrc
 		fi
@@ -276,12 +279,12 @@ importing()
 	echo
 
 	echo "Do you want to edit it with vi?"
-	echo "Enter EDIT (all upper case) if you do"
+	echo "Enter 'edit' if you do"
 	echo -n "or just hit enter if you don't: "
 	unset EDIT
 	read EDIT
 
-	if [ "x$EDIT" = "xEDIT" ]
+	if [ "x$EDIT" = "xedit" ]
 	then
 		vi /etc/tor/torrc
 	fi
@@ -293,9 +296,9 @@ importing()
 	echo 
 
 	echo "Do you want to import a secret key or generate one?"
-	echo "NOTE: Only FTP and SCP are supported"
+	echo "NOTE: Only ftp and scp are supported"
 	echo
-	echo -n "Enter IMPORT or GENERATE (all upper case): "
+	echo -n "Enter 'import' or 'generate': "
 	if [ -f /var/tor/keys/secret_id_key ]
 	then
 		echo
@@ -306,17 +309,17 @@ importing()
 	unset IMPORTSSL
 	read IMPORTSSL
 
-	if [ "x$IMPORTSSL" = "xIMPORT" ]
+	if [ "x$IMPORTSSL" = "ximport" ]
 	then
 
 		echo "Importing secret key ..."
 		echo
 
-		echo -n "Enter FTP or SCP (all upper case):"
+		echo -n "Enter 'ftp' or 'scp':"
 		unset FTP
 		read FTP
 
-		echo -n "Enter the hostname/IP of the FTP/SSH server: "
+		echo -n "Enter the hostname/IP of the ftp/ssh server: "
 		unset HOST
 		read HOST
 	
@@ -324,13 +327,13 @@ importing()
 		unset FTPPATH
 		read FTPPATH
 
-		echo -n "Enter the username (or anonymous) of the FTP/SSH account: "
+		echo -n "Enter the username (or anonymous) of the ftp/ssh account: "
 		unset USER
 		read USER
 
-		if [ "x$FTP" = "xFTP" ]
+		if [ "x$FTP" = "xftp" ]
 		then
-			echo -n "Enter the password of the FTP account (will not echo): "
+			echo -n "Enter the password of the ftp account (will not echo): "
 			unset PASS
 			stty -echo
 			read PASS
@@ -339,11 +342,11 @@ importing()
 
 			ftpget -u $USER -p $PASS $HOST /var/tor/keys/secret_id_key $FTPPATH || return 3
 
-		elif [ "x$FTP" = "xSCP" ] 
+		elif [ "x$FTP" = "xscp" ] 
 		then
 			scp $USER@$HOST:$FTPPATH /var/tor/keys/secret_id_key || return 3
 		else
-			echo "Please specify whether you want to use STATIC or DYNAMIC ip assignment."
+			echo "Please specify whether you want to use 'ftp' or 'scp'."
 			return 3
 		fi
 
@@ -354,7 +357,7 @@ importing()
 		echo "<secret_id_key successfully imported>"
 		echo
 
-	elif [ "x$IMPORTSSL" = "xGENERATE" ]
+	elif [ "x$IMPORTSSL" = "xgenerate" ]
 	then
 
 		rm -f /var/tor/keys/secret_id_key
@@ -384,13 +387,13 @@ exporting()
 	echo "*** EXPORTING TORRC *** "
 	echo 
 	echo "Do you want to export your torrc?"
-	echo "NOTE: Only FTP and SCP are supported"
-	echo "Enter EXPORT (all upper case) if you do"
+	echo "NOTE: Only ftp and scp are supported"
+	echo "Enter 'export' if you do"
 	echo -n "or just hit enter if you don't: "
 	unset EXPORTTORRC
 	read EXPORTTORRC
 
-	if [ "x$EXPORTTORRC" = "xEXPORT" ]
+	if [ "x$EXPORTTORRC" = "xexport" ]
 	then
 		if [ ! -f /etc/tor/torrc ]
 		then
@@ -399,11 +402,11 @@ exporting()
 			echo "Exporting torrc ..."
 			echo
 
-			echo -n "Enter FTP or SCP (all upper case):"
+			echo -n "Enter 'ftp' or 'scp':"
 			unset FTP
 			read FTP
 
-			echo -n "Enter the hostname/IP of the FTP server: "
+			echo -n "Enter the hostname/IP of the ftp server: "
 			unset HOST
 			read HOST
 	
@@ -411,13 +414,13 @@ exporting()
 			unset FTPPATH
 			read FTPPATH
 
-			echo -n "Enter the username (or anonymous) of the FTP account: "
+			echo -n "Enter the username (or anonymous) of the ftp account: "
 			unset USER
 			read USER
 
-			if [ "x$FTP" = "xFTP" ]
+			if [ "x$FTP" = "xftp" ]
 			then
-				echo -n "Enter the password of the FTP account (will not echo): "
+				echo -n "Enter the password of the ftp account (will not echo): "
 				unset PASS
 				stty -echo
 				read PASS
@@ -426,11 +429,11 @@ exporting()
 
 				ftpput -u $USER -p $PASS $HOST $FTPPATH /etc/tor/torrc || return 1
 
-			elif [ "x$FTP" = "xSCP" ]
+			elif [ "x$FTP" = "xscp" ]
 			then
 				scp /etc/tor/torrc $USER@$HOST:$FTPPATH || return 1
 			else
-				echo "Please specify whether you want to use FTP or SCP."
+				echo "Please specify whether you want to use 'ftp' or 'scp'."
 				return 1
 			fi
 
@@ -445,13 +448,13 @@ exporting()
 	echo "*** EXPORTING SECRET KEY  *** "
 	echo 
 	echo "Do you want to export your secret_id_key?"
-	echo "NOTE: Only FTP and SCP are supported"
-	echo "Enter EXPORT (all upper case) if you do"
+	echo "NOTE: Only ftp and scp are supported"
+	echo "Enter 'export' if you do"
 	echo -n "or just hit enter if you don't: "
 	unset EXPORTSSL
 	read EXPORTSSL
 
-	if [ "x$EXPORTSSL" = "xEXPORT" ]
+	if [ "x$EXPORTSSL" = "xexport" ]
 	then
 		if [ ! -f /var/tor/keys/secret_id_key ]
 		then
@@ -460,7 +463,7 @@ exporting()
 			echo "Exporting secret_id_key ..."
 			echo
 
-			echo -n "Enter the hostname/IP of the FTP server: "
+			echo -n "Enter the hostname/IP of the ftp server: "
 			unset HOST
 			read HOST
 	
@@ -468,13 +471,13 @@ exporting()
 			unset FTPPATH
 			read FTPPATH
 
-			echo -n "Enter the username (or anonymous) of the FTP account: "
+			echo -n "Enter the username (or anonymous) of the ftp account: "
 			unset USER
 			read USER
 
-			if [ "x$FTP" = "xFTP" ]
+			if [ "x$FTP" = "xftp" ]
 			then
-				echo -n "Enter the password of the FTP account (will not echo): "
+				echo -n "Enter the password of the ftp account (will not echo): "
 				unset PASS
 				stty -echo
 				read PASS
@@ -483,11 +486,11 @@ exporting()
 
 				ftpput -u $USER -p $PASS $HOST $FTPPATH /var/tor/keys/secret_id_key || return 2
 
-			elif [ "x$FTP" = "xSCP" ]
+			elif [ "x$FTP" = "xscp" ]
 			then
 				scp /var/tor/keys/secret_id_key $USER@$HOST:$FTPPATH || return 2
 			else
-				echo "Please specify whether you want to use FTP or SCP."
+				echo "Please specify whether you want to use 'ftp' or 'scp'."
 				return 2
 			fi
 
@@ -568,6 +571,10 @@ do
 				echo "*** FAILED udhcp acquire address ***"
 			elif [ $ERR -eq 7 ]
 			then
+				NETWORK=0
+				echo "*** FAILED to establish ftp or scp ***"
+			elif [ $ERR -eq 8 ]
+			then
 				NETWORK=0 
 				echo "*** FAILED establish address ***"
 			else
@@ -599,9 +606,9 @@ do
 				unset DATEHOST
 				read DATEHOST
 
-				rdate -s $DATEHOST || echo "*** ERR date was not set ***"
+				rdate -s $DATEHOST || echo "*** FAILED date was not set ***"
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 			fi
 
 			echo
@@ -629,7 +636,7 @@ do
 				echo
 				nslookup www.google.com | more
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 			fi
 
 			echo
@@ -646,15 +653,15 @@ do
 				unset RIP
 				RIP=$( route -n | grep "^0.0.0.0" | awk '{ print $2 }' )
 				ping -c 3 $RIP >/dev/null 2>&1 \
-					&& echo "OK: Router $RIP Reacheable" \
-					|| echo "ERR: Router $RIP Unreacheable"
+					&& echo "OK Router $RIP Reacheable" \
+					|| echo "FAILED Router $RIP Unreacheable"
 
 				echo
 
 				NAME=$( cat /etc/resolv.conf | grep nameserver | awk '{ print $2}' )
 				nslookup www.google.com >/dev/null 2>&1 \
-					&& echo "OK: Nameserver $NAME Working" \
-					|| echo "ERR: Nameserver $NAME NOT Working"
+					&& echo "OK Nameserver $NAME Working" \
+					|| echo "FAILED Nameserver $NAME NOT Working"
 
 				echo
 				echo "Do you want to ping a hostname/IP address?"
@@ -665,8 +672,8 @@ do
 				if [ "x$PING" != "x" ]
 				then
 					ping -c 3 $PING >/dev/null 2>&1 \
-						&& echo "OK: Host $PING Reacheable" \
-						|| echo "ERR: Host $PING Unreacheable"
+						&& echo "OK Host $PING Reacheable" \
+						|| echo "FAILED Host $PING Unreacheable"
 
 					echo
 					echo -n "Hit enter to continue: "
@@ -674,7 +681,7 @@ do
 					echo
 				fi
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 				echo
 				echo -n "Hit enter to continue: "
 				read DUMMY
@@ -690,7 +697,7 @@ do
 			then
 				netstat -ntl | more
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 			fi
 
 			echo
@@ -706,7 +713,7 @@ do
 			then
 				netstat -nt | more
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 			fi
 
 			echo
@@ -746,7 +753,7 @@ do
 					echo "<Tor is configured (but not started yet)>"
 				fi
 			else
-				echo "*** ERR network is not up yet! ***"
+				echo "*** FAILED network is not up yet! ***"
 			fi
 
 			echo
@@ -778,11 +785,11 @@ do
 			else
 				if [ $NETWORK -eq 0 ]
 				then
-					echo "*** ERR network is not up yet! ***"
+					echo "*** FAILED network is not up yet! ***"
 				fi
 				if [ $CONFIGURED -eq 0 ]
 				then
-					echo "*** ERR Tor is not configured yet! ***"
+					echo "*** FAILED Tor is not configured yet! ***"
 				fi
 			fi
 
@@ -802,11 +809,11 @@ do
 			else
 				if [ $NETWORK -eq 0 ]
 				then
-					echo "*** ERR network is not up yet! ***"
+					echo "*** FAILED network is not up yet! ***"
 				fi
 				if [ $CONFIGURED -eq 0 ]
 				then
-					echo "*** ERR Tor is not configured yet! ***"
+					echo "*** FAILED Tor is not configured yet! ***"
 				fi
 			fi
 
@@ -826,11 +833,11 @@ do
 			else
 				if [ $NETWORK -eq 0 ]
 				then
-					echo "*** ERR network is not up yet! ***"
+					echo "*** FAILED network is not up yet! ***"
 				fi
 				if [ $CONFIGURED -eq 0 ]
 				then
-					echo "*** ERR Tor is not configured yet! ***"
+					echo "*** FAILED Tor is not configured yet! ***"
 				fi
 			fi
 
@@ -878,11 +885,11 @@ do
 			else
 				if [ $NETWORK -eq 0 ]
 				then
-					echo "*** ERR network is not up yet! ***"
+					echo "*** FAILED network is not up yet! ***"
 				fi
 				if [ $CONFIGURED -eq 0 ]
 				then
-					echo "*** ERR Tor is not configured yet! ***"
+					echo "*** FAILED Tor is not configured yet! ***"
 				fi
 			fi
 
@@ -943,5 +950,3 @@ do
 	esac
 
 done
-
-
